# NOTE: If you see a FileNotFoundError, please generate the debate
# with the below `debate_group` and `debate_structure` first before 
# running evaluation!

model: "mistral:7b" 
debate_group: "neutral_republican_democrat"  # options: "neutral_republican", "neutral_democrat", "neutral_republican_democrat"
debate_structure: "structured"  # options: "structured", "unstructured"
scale: "1 to 7"  # Likert scale options: "1 to 7" or "-3 to 3"; "binary" for disagreement/agreement metric
num_rounds: 10 # All debates in the chosen directory should have same number of rounds.
num_debates: 10 # Run evaluation on the recent 10 debates/transcripts only
