model: "mistral:7b"
debate_group: "neutral_republican"  # options: "neutral_republican", "neutral_democrat", "neutral_republican_democrat"
debate_structure: "unstructured"  # options: "structured", "unstructured"
scale: "1 to 7"  # Likert scale options: "1 to 7" or "-3 to 3"
