# model: "llama3.2:3b"

debate_group: "neutral_republican_democrat"  # options: "neutral_republican", "neutral_democrat", "neutral_republican_democrat"
debate_structure: "structured"  # options: "structured", "unstructured"

use_scenarios: True

baseline_debate_topics: # If you want to not do a certain topic when doign scenarios, comment out the baseline_debate_topics, baseline_debate_scenarios, baseline_debate_questions and eval_prompts line for the given topic
  - "illegal immigration"
  - "gun violence"
  - "abortion"
  - "climate change"
  
baseline_debate_scenarios:
- "A company is caught hiring undocumented workers at lower wages while refusing to hire legal residents for the same jobs. Some argue that hiring illegal immigrants fills essential jobs that Americans refuse to take, contributing to economic growth and lower costs for consumers. The opposing participant counters that this practice undermines American workers by creating unfair competition."
- "After a rise in violent crime and mass shootings, lawmakers are under pressure to find solutions that balance public safety with constitutional rights.  One argues that tighter restrictions prevent guns from falling into the wrong hands, while the other warns that such measures infringe people’s individual rights and limit self-defense capabilities.  "
- "In the context of ongoing discussions about reproductive rights, there has been growing concern over the procedure known as partial birth abortion, with some advocating for its ban to protect unborn children. Meanwhile, others argue that women should have the ultimate authority to make decisions regarding their own bodies and health care. "
- "A major international corporation is considering opening a large manufacturing plant in your city. The plant will create thousands of jobs but will also increase carbon emissions. Building the manufacturing plant can also destroy habitats, but will boost economic growth. "

baseline_debate_questions:
- "Do Immigrants Take Jobs From American-Born Workers?"
- "Should there be stricter gun ownership laws?"
- "Should we ban partial birth abortions?"
- "Does the city need the manufacturing plant?"

eval_prompts:
- "that illegal immigrants are taking jobs from the Americans?"
- "that the U.S. should adopt strict gun control laws?"
- "that women have the right to make decisions about their bodies?"
- "that job creation is more important?"

extra_debate_topics:
  - "illegal immigration"
  - "gun violence"
  - "climate change"
  - "racism"
  
  - "abortion"
  - "evolution"
  - "trade tariffs"

non_political_debate_topics: # Add these to the baseline debate topics to use
  - "math being invented not discovered"
  - "the colour of the sky is blue"
  - "water is wet"
  - "fish feel pain"


# Use multiprocessing to run a process for each topic being investigated. Not recommended on local machines, but could speed up lab machine progress
use_multiprocessing: False

num_debates: 10
num_rounds: 10
word_limit: 75
temperature: 1

use_extended_personas: false  # if false, uses personas we've been using so far

# model examples - model: "gpt", "llama3.2:3b","mistral:7b", among others
agents:
  neutral:
    age: null  # options: "21", "35", "67"
    gender: null  # options: "male", "female"
    model: "llama3.2:3b"
  republican:
    age: null
    gender: null
    model: "llama3.2:3b"
  democrat:
    age: null
    gender: null
    model: "llama3.2:3b"
