# model: "llama3.2:3b"

debate_group: "neutral_republican_democrat"  # options: "neutral_republican", "neutral_democrat", "neutral_republican_democrat"
debate_structure: "structured"  # options: "structured", "unstructured"

baseline_debate_topics:
 - "math being invented not discovered"
 - "the colour of the sky is blue"
 - "water is wet"
 - "fish feel pain"



extra_debate_topics:
  - "illegal immigration"
  - "gun violence"
  - "climate change"
  - "racism"
  
  - "abortion"
  - "evolution"
  - "trade tariffs"

# Use multiprocessing to run a process for each topic being investigated. Not recommended on local machines, but could speed up lab machine progress
use_multiprocessing: false

num_debates: 10
num_rounds: 10
# model examples - model: "gpt", "llama3.2:3b","mistral:7b", among others
agents:
  neutral:
    age: null
    gender: null
    model: "llama3.2:3b"
  republican:
    age: null
    gender: null
    model: "llama3.2:3b"
  democrat:
    age: null
    gender: null
    model: "llama3.2:3b"
